### ISSUE TITLE
[Question]: I can't get uploader to work

### ISSUE THREAD

**Issue by Igmat** [Digitalroot-Valheim/Digitalroot.ModUploader#11]
### How are you playing the game?

Multiplayer - My Client Hosts Server

### What happened?

Guys, I'm trying to move from original `NexusUploader` to `Digitalroot.OdinPlusModUploader`.
The problem is I can't see `nexusid` cookie mentioned in docs.

Does it still possible to publish mods to nexus automatically?

### To Reproduce

1. Go to `nexusmods.com`
2. Login
3. Go to developer tools
4. See `nexusid` cookie missing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
It still works. I used it today.

Have you tried both Firefox and Chrome?
