### ISSUE TITLE
[Feature]: Changelog

### ISSUE THREAD

**Issue by luxzg** [Digitalroot-Valheim/Digitalroot.ModUploader#12]
### Problem

You might want to add changelog from GitHub to be automatically use for both changelog field (drop-down) on Nexus Mods, and as file description as well. Eg. Plugin info is 10 minor builds behind in changelog, and file descriptions just point to automatic Odin update. 

### Solution

It would be way more helpful for average user to see something like "v1.4.16
Automated NuGet Dependency Updates"
(even if they don't get what is NuGet)

### Alternatives

Going manually to git releases and checking there, not many people would do that

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
That is a good idea.

**Comment by Digitalroot** [comment]
Updated documentation on Nexus. I'll try to keep it up today.
