### ISSUE TITLE
[Feature]: NexusMods: Prevent "old versions" from moving to Archive

### ISSUE THREAD

**Issue by ividyon** [Digitalroot-Valheim/Digitalroot.ModUploader#14]
### Problem

When a new version of a file is uploaded, the old file wanders directly into the "Archive" section, inaccessible for users.
When using the regular Nexus website, the file would instead wander into "Old Files" and still be accessible.

### Solution

Allow customizing the category to which the old file gets moved.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
Let me think about this....

**Comment by Digitalroot** [comment]
Added
