### ISSUE TITLE
[Bug]: Error: OK: You don't have the permission to edit this mod..

### ISSUE THREAD

**Issue by ividyon** [Digitalroot-Valheim/Digitalroot.ModUploader#15]
### How are you playing the game?

Single Player - No Server

### What happened?

I've not changed anything about my GH actions or the project setup since the last time it worked. It has just kind of appeared by itself.

The last time I released was a few months ago, so to be safe I re-applied the API key and session cookie in my GitHub secrets, but to no avail.

### To Reproduce

Check the affected workflow run:

https://github.com/ividyon/WitchyBND/actions/runs/7444744063/job/20252176360

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
Run this in your workflow. 

          drmu nx check

This should output which part is failing. I've never had to update the api key. For me it has always been the cookie. There seems to be a state where the cookie is kinda valid and you still get the permission error. I think it might have something to do with the session being active for cloudflare but not for nx. Log out of nexus and relog in. Grab that new cookie value.

**Comment by Digitalroot** [comment]
The cookies are good for about 30 days before they "timeout" for inactivity. If you release monthly the cookie can last a long time.

**Comment by ividyon** [comment]
That's quite strange... doing it again by logging out, clearing my cookies and logging back in with a fresh cache seems to have helped. Thank you!

**Comment by ividyon** [comment]
May have to reopen this;

https://github.com/ividyon/WitchyBND/actions/runs/8010208141/job/21880779583

As you can see, the Check successfully validates the cookies, but then the uploads fail anyway. ("Check mod uploader" step)

Just now, I updated the session cookie again, and it's fixed once again.

https://github.com/ividyon/WitchyBND/actions/runs/8171986796/job/22341521632

The cookie also expired faster than 30 days.

**Comment by Digitalroot** [comment]
I wonder if is a session timeout w/ cloudflare. I have used the Web interface and have had to log all the way out before.
