### ISSUE TITLE
[Bug]: Chunk 1 of 1 does not already exist

### ISSUE THREAD

**Issue by alcmoe** [Digitalroot-Valheim/Digitalroot.ModUploader#17]
### How are you playing the game?

Single Player - No Server

### What happened?

I use github workflow,when update mod,it shows "Chunk 1 of 1 does not already exist"

### To Reproduce

https://github.com/alcmoe/FreezeTimeMultiplayer/blob/master/.github/workflows/dotnet.yml

### Screenshots

![image](https://github.com/Digitalroot-Valheim/Digitalroot.ModUploader/assets/9844277/f4229a8d-5998-48d4-8a3e-01a16af2b3b9)

### Log File

[log](https://github.com/alcmoe/FreezeTimeMultiplayer/actions/runs/8598959346/job/23560878066)

**Comment by Digitalroot** [comment]
That looks like a 500 http error. I get this when nx is having issues. When this happens I am also unable to upload via the nx website. Is it still an issue?

**Comment by alcmoe** [comment]
> That looks like a 500 http error. I get this when nx is having issues. When this happens I am also unable to upload via the nx website. Is it still an issue?这看起来像一个 500 http 错误。当 nx 遇到问题时，我会得到这个。发生这种情况时，我也无法通过 nx 网站上传。这仍然是一个问题吗？

I could not reproduce it anymore, I think this issue could be closed, but I still got [issue#16](https://github.com/Digitalroot-Valheim/Digitalroot.ModUploader/issues/16) lol
