### ISSUE TITLE
[Bug]: sid_develop cookie is gone from redesigned Nexus page

### ISSUE THREAD

**Issue by ividyon** [Digitalroot-Valheim/Digitalroot.ModUploader#18]
### How are you playing the game?

Single Player - No Server

### What happened?

You can no longer get the sid_develop cookie from Nexus, so you cannot use this tool.

The new cookies don't have the expected encoded JSON format.

### To Reproduce

Log into Nexus, check the cookies.

![2024-05-22_00-58-57](https://github.com/Digitalroot-Valheim/Digitalroot.ModUploader/assets/1077140/18943b6e-9b2f-4315-a515-cc939aa1def1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
Looking into this.
